//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Applicant()
        {
            this.App_AcknowledgementData = new HashSet<App_AcknowledgementData>();
            this.App_AllocationData = new HashSet<App_AllocationData>();
            this.App_ApplicantStatus = new HashSet<App_ApplicantStatus>();
            this.App_AttachmentDocument = new HashSet<App_AttachmentDocument>();
            this.App_ExistingOwnership = new HashSet<App_ExistingOwnership>();
            this.App_Financial = new HashSet<App_Financial>();
            this.App_WaitingList = new HashSet<App_WaitingList>();
        }
    
        public long ApplicantID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string IDNumber { get; set; }
        public string ResidentialAddress { get; set; }
        public string PostalAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Occupation { get; set; }
        public decimal IncomePerMonth { get; set; }
        public string NameOfEmployer { get; set; }
        public string SpouseSurname { get; set; }
        public string SpouseFirstname { get; set; }
        public string SpouseIDNumber { get; set; }
        public string SpouseResidentialAddress { get; set; }
        public string SpousePostalAddress { get; set; }
        public string SpouseTelephoneNumber { get; set; }
        public string SpouseFaxNumber { get; set; }
        public string SpouseEmailAddress { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<decimal> SpouseIncomePerMonth { get; set; }
        public string SpouseNameOfEmployer { get; set; }
        public long PlotTypeID { get; set; }
        public long ErfSizeID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public Nullable<bool> SignedByApplicant { get; set; }
        public Nullable<bool> SignedBySpouse { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<bool> StageApplication { get; set; }
        public Nullable<bool> StageAllocation { get; set; }
        public Nullable<bool> StageSale { get; set; }
        public Nullable<bool> StageRegistration { get; set; }
        public Nullable<bool> StageValuation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AcknowledgementData> App_AcknowledgementData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AllocationData> App_AllocationData { get; set; }
        public virtual Sys_ErfSize Sys_ErfSize { get; set; }
        public virtual Sys_PlotType Sys_PlotType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_ApplicantStatus> App_ApplicantStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AttachmentDocument> App_AttachmentDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_ExistingOwnership> App_ExistingOwnership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Financial> App_Financial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_WaitingList> App_WaitingList { get; set; }
    }
}
