//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Allocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Allocation()
        {
            this.App_AllocationData = new HashSet<App_AllocationData>();
        }
    
        public long AllocationID { get; set; }
        public long PlotTypeID { get; set; }
        public long MonthID { get; set; }
        public long AllocationYear { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public byte[] AllocationLetter { get; set; }
        public string AllocationLetterFileName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Sys_Month Sys_Month { get; set; }
        public virtual Sys_PlotType Sys_PlotType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AllocationData> App_AllocationData { get; set; }
    }
}
