//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Acknowledgment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Acknowledgment()
        {
            this.App_AcknowledgementData = new HashSet<App_AcknowledgementData>();
        }
    
        public long AcknowledgmentID { get; set; }
        public long MonthID { get; set; }
        public long AcknowledmentYear { get; set; }
        public System.DateTime AcknowledmentDate { get; set; }
        public byte[] AcknowledgmentLetter { get; set; }
        public string AcknowledgmentLetterFileName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AcknowledgementData> App_AcknowledgementData { get; set; }
        public virtual Sys_Month Sys_Month { get; set; }
    }
}
