//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_ExistingOwnership
    {
        public long ExistingOwnershipID { get; set; }
        public long ApplicantID { get; set; }
        public long ErfNumberID { get; set; }
        public string ErfSize { get; set; }
        public string ReferenceNumber { get; set; }
        public string Improvement { get; set; }
        public string LeaseAggreement { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<System.DateTime> DateOfFirstOccupation { get; set; }
        public string WhoIsOccupyingTheErf { get; set; }
        public string WhoIsResponsibleForPayment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual App_Applicant App_Applicant { get; set; }
        public virtual App_Erf App_Erf { get; set; }
    }
}
