//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_WaitingList
    {
        public long WaitingListID { get; set; }
        public Nullable<long> WaitingListNumber { get; set; }
        public Nullable<long> ApplicantID { get; set; }
        public Nullable<long> UserDefined1 { get; set; }
        public string UserDefined2 { get; set; }
    
        public virtual App_Applicant App_Applicant { get; set; }
    }
}
