//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Erf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Erf()
        {
            this.App_AllocationData = new HashSet<App_AllocationData>();
            this.App_ExistingOwnership = new HashSet<App_ExistingOwnership>();
        }
    
        public long ErfNumberID { get; set; }
        public string ErfNumber { get; set; }
        public long ErfSize { get; set; }
        public long ErfAreaID { get; set; }
        public long PlotTypeID { get; set; }
        public long ErfTownshipID { get; set; }
        public string ErfComment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> ErfPurchasePrice { get; set; }
        public Nullable<decimal> ErfAdminFees { get; set; }
        public Nullable<decimal> ErfVat { get; set; }
        public Nullable<bool> StageAllocation { get; set; }
        public Nullable<bool> StageSale { get; set; }
        public Nullable<bool> StageRegistration { get; set; }
        public Nullable<bool> StageValuation { get; set; }
        public Nullable<decimal> ErfTotalPurchasePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_AllocationData> App_AllocationData { get; set; }
        public virtual Sys_ErfArea Sys_ErfArea { get; set; }
        public virtual Sys_ErfTownship Sys_ErfTownship { get; set; }
        public virtual Sys_PlotType Sys_PlotType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_ExistingOwnership> App_ExistingOwnership { get; set; }
    }
}
