//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSContent
    {
        public long SmsID { get; set; }
        public string SmsMessage { get; set; }
        public Nullable<bool> ActiveSMS { get; set; }
        public Nullable<System.DateTime> DATETIMESTAMP { get; set; }
        public long SmsTypeID { get; set; }
    
        public virtual SmsType SmsType { get; set; }
    }
}
