//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsData
    {
        public long SmsDataID { get; set; }
        public long SMSInstanceID { get; set; }
        public string CellNumber { get; set; }
        public string SmsMessage { get; set; }
    
        public virtual SmsInstance SmsInstance { get; set; }
    }
}
