//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmsInstance()
        {
            this.SmsDatas = new HashSet<SmsData>();
        }
    
        public long SMSInstanceID { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public long SmsTypeID { get; set; }
        public Nullable<long> MonthID { get; set; }
        public Nullable<long> Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmsData> SmsDatas { get; set; }
        public virtual Sys_Month Sys_Month { get; set; }
        public virtual SmsType SmsType { get; set; }
    }
}
