//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ErfCost
    {
        public long ErfCostID { get; set; }
        public long PlotTypeID { get; set; }
        public decimal CostPerSqm { get; set; }
        public decimal AdminFees { get; set; }
    
        public virtual Sys_PlotType Sys_PlotType { get; set; }
    }
}
